name: Flame CI
on: [push, pull_request]
env:
  CLICOLOR_FORCE: 1
jobs:
  ci:
    name: Go E2E Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        rust: [stable]
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Start Flame
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./compose.yaml"
      - name: Install gRPC
        run: |
          sudo apt-get update && sudo apt-get install -y protobuf-compiler
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.24.x
          cache: true
      - name: Install Go dependencies
        run: |
          go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.30.0
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.3.0
      - name: Run Go E2E Test
        run: |
          make sdk-go-test
      - name: Run MCP E2E Test
        run: |
          cd examples/mcp && make test