name: Flame CI
on: [push, pull_request]
env:
  CLICOLOR_FORCE: 1
jobs:
  ci:
    name: E2E Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        rust: [stable]
        os: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # - name: Setup Kind Cluster
      #   uses: helm/kind-action@v1
      #   with:
      #     config: ci/kind.yaml
      #     cluster_name: flame-ci-cluster
      # - name: Build images
      #   run: |
      #     make ci-image
      # - name: Load images
      #   run: |
      #     kind load docker-image --name flame-ci-cluster xflops/flame-session-manager:latest
      #     kind load docker-image --name flame-ci-cluster xflops/flame-executor-manager:latest
      #     kind load docker-image --name flame-ci-cluster xflops/flame-console:latest
      # - name: Deploy Flame
      #   run: |
      #     kubectl apply -k installer/
      - name: Start Flame
        uses: hoverkraft-tech/compose-action@v2.0.1

      - name: Install gRPC
        run: |
          sudo apt-get update && sudo apt-get install -y protobuf-compiler
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true
      - name: Run E2E Test
        run: |
          cargo test -- --nocapture
